name: noahmp_emulator
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pytorch>=2.0
  - xarray>=2023.1
  - pandas>=2.0
  - numpy>=1.24
  - scipy>=1.10
  - matplotlib>=3.7
  - tqdm>=4.65
  - netcdf4>=1.6
